// export const ITableStoriesData = {
//   title: '查詢結果',
//   perPage: 5,
//   fields: [
//     { key: 'eventId', label: '事件編號', sortable: true, visible: false },
//     { key: 'eventType', label: '事件類型', sortable: false },
//     { key: 'eventDesc', label: '事件描述', sortable: true, visible: true },
//     { key: 'eventRate', label: '事件比重(0~100)', sortable: true, visible: false },
//     { key: 'eventRiskScore', label: '風險事件評分(權重*配分)', sortable: true },
//     { key: 'countRiskScoreFrequency', label: '計算週期' },
//     { key: 'creator', label: '建立者', sortable: true },
//     { key: 'modifier', label: '修改者' },
//   ],
//   items: [
//     {
//       eventId: 'A0001',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 10,
//       eventRiskScore: 8,
//       countRiskScoreFrequency: '每周',
//       creator: 'Mrs. A',
//       modifier: 'Mrs. A',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//     {
//       eventId: 'A0002',
//       eventType: '警示',
//       eventDesc: '風險過高',
//       eventRate: 20,
//       eventRiskScore: 16,
//       countRiskScoreFrequency: '每日',
//       creator: 'Mrs. B',
//       modifier: 'Mrs. B',
//     },
//   ],
// };
