spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://192.168.57.201:9981;databaseName=eip;encrypt=true;trustServerCertificate=true
#    url: jdbc:sqlserver://localhost:1433;database=eip;encrypt=false
    username: eip
#    username: sa
    password: iisi@12345
#    password: iisi@123
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
flowable:
  database-schema-update: true
server:
  port: 9973

bpm:
  token: QAZWSXEDCRffvYTHnujkljkfyffd14651456uhweuhuijwdijoichchuhqiheciqhoieh
  url: http://localhost:8080