spring:
  datasource:
    url: jdbc:sqlserver://192.168.3.91;databaseName=eip;encrypt=true;trustServerCertificate=true
flowable:
  database-schema-update: true
server:
  port: 9973
  error:
    include-message: always

bpm:
  url: http://192.168.2.91
setting:
  path: /mnt/stsdat/eip/setting.txt
  decode: /mnt/stsdat/eip/decode.txt