spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://192.168.3.191;databaseName=eip;encrypt=true;trustServerCertificate=true
    username: eip
    password: iisi@12345
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 30000
      maximum-pool-size: 10
flowable:
  database-schema-update: true
server:
  port: 9973
  error:
    include-message: always

bpm:
  url: http://127.0.0.1