create table BPM_ISMS_L410
(
    FORM_ID                          varchar(50) not null
        constraint BPM_ISMS_L410_pk
            primary key,
    PROCESS_INSTANCE_ID              varchar(50) not null,
    APPLY_DATE                       datetime    not null,
    FIL_EMPID                        nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    FIL_NAME                         nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    FIL_UNIT                         nvarchar(100) collate Chinese_Taiwan_Stroke_CS_AS not null,
    APP_EMPID                        nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    APP_NAME                         nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    APP_ENG_NAME                     nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    APP_UNIT                         nvarchar(30) collate Chinese_Taiwan_Stroke_CS_AS not null,
    POSITION                         nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    EXT_NUM                          nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_SUBMIT                        nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    APP_REASON                       nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    IS_ENABLE_DATE                   nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    ENABLE_DATE                      datetime,
    IS_OTHER                         nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_REASON                     nvarchar(100) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_HR_SYS                        nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    HR_SYS                           nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    HR_SYS_CHANGE                    nvarchar(100) collate Chinese_Taiwan_Stroke_CS_AS,
    HR_SYS_ADM_UNIT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    HR_SYS_STATUS                    nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    HR_SYS_ENABLE_DATE               datetime,
    HR_SYS_ADM_NAME                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_AD_SYS                        nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    AD_ACCOUNT                       nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    AD_SYS                           nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    AD_SYS_CHANGE                    nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    AD_SYS_ADM_UNIT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    AD_SYS_STATUS                    nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    AD_SYS_ENABLE_DATE               datetime,
    AD_SYS_ADM_NAME                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_MEETING_ROOM                  nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    MEETING_ROOM                     nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    MEETING_ROOM_CHANGE              nvarchar(100) collate Chinese_Taiwan_Stroke_CS_AS,
    MEETING_ROOM_ADM_UNIT            nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    MEETING_ROOM_STATUS              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    MEETING_ROOM_ENABLE_DATE         datetime,
    MEETING_ROOM_ADM_NAME            nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_OD_SYS                        nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    OD_SYS_ROLE                      nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OD_SYS                           nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    OD_SYS_OTHER                     nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OD_SYS_ADM_UNIT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OD_SYS_STATUS                    nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OD_SYS_ENABLE_DATE               datetime,
    OD_SYS_ADM_NAME                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_EMAIL_SYS                     nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_SYS_ACCOUNT                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_SYS                        nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_APPLY1                     nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_APPLY2                     nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_SYS_CHANGE                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_SYS_ADM_UNIT               nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_SYS_STATUS                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    EMAIL_SYS_ENABLE_DATE            datetime,
    EMAIL_SYS_ADM_NAME               nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_WEB_SITE                      nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    IS_PCC_WWW                       nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    IS_PCC_HOME                      nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    WEB_SITE                         nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    IS_UNIT_ADM                      nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    IS_UNIT_DATA_MGR                 nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    IS_WEB_SITE_OTHER                nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    WEB_SITE_OTHER                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    WEB_SITE_ADM_UNIT                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    WEB_SITE_STATUS                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    WEB_SITE_ENABLE_DATE             datetime,
    WEB_SITE_ADM_NAME                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_PCC_PIS                       nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    PCC_PIS_ACCOUNT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    PCC_PIS                          nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    PCC_PIS_CHANGE                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    PCC_PIS_ADM_UNIT                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    PCC_PIS_STATUS                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    PCC_PIS_ENABLE_DATE              datetime,
    PCC_PIS_ADM_NAME                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_ENG_AND_PRJ_INFO_SYS          nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    ENG_AND_PRJ_INFO_SYS_ACCOUNT     nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    ENG_AND_PRJ_INFO_SYS             nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    ENG_AND_PRJ_INFO_SYS_CHANGE      nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    ENG_AND_PRJ_INFO_SYS_ADM_UNIT    nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    ENG_AND_PRJ_INFO_SYS_STATUS      nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    ENG_AND_PRJ_INFO_SYS_ENABLE_DATE datetime,
    ENG_AND_PRJ_INFO_SYS_ADM_NAME    nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_REV_SYS                       nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    REV_SYS_ACCOUNT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REV_SYS                          nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    REV_SYS_CHANGE                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REV_SYS_ADM_UNIT                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REV_SYS_STATUS                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REV_SYS_ENABLE_DATE              datetime,
    REV_SYS_ADM_NAME                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_REC_SYS                       nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    REC_SYS_ACCOUNT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REC_SYS                          nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    REC_SYS_CHANGE                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REC_SYS_ADM_UNIT                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REC_SYS_STATUS                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    REC_SYS_ENABLE_DATE              datetime,
    REC_SYS_ADM_NAME                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_BID_SYS                       nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    BID_SYS_ACCOUNT                  nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    BID_SYS                          nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    BID_SYS_CHANGE                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    BID_SYS_ADM_UNIT                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    BID_SYS_STATUS                   nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    BID_SYS_ENABLE_DATE              datetime,
    BID_SYS_ADM_NAME                 nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_OTHER_SYS1                    nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1_SERVER_NAME           nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1_ACCOUNT               nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1                       nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1_CHANGE                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1_ADM_UNIT              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1_STATUS                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS1_ENABLE_DATE           datetime,
    OTHER_SYS1_ADM_NAME              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_OTHER_SYS2                    nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2_SERVER_NAME           nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2_ACCOUNT               nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2                       nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2_CHANGE                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2_ADM_UNIT              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2_STATUS                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS2_ENABLE_DATE           datetime,
    OTHER_SYS2_ADM_NAME              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    IS_OTHER_SYS3                    nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3_SERVER_NAME           nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3_ACCOUNT               nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3                       nvarchar collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3_CHANGE                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3_ADM_UNIT              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3_STATUS                nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    OTHER_SYS3_ENABLE_DATE           datetime,
    OTHER_SYS3_ADM_NAME              nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    PROCESS_INSTANCE_STATUS          nvarchar default '0' collate Chinese_Taiwan_Stroke_CS_AS,
    UPDATE_USER                      nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS,
    UPDATE_TIME                      datetime,
    CREATE_USER                      nvarchar(20) collate Chinese_Taiwan_Stroke_CS_AS not null,
    CREATE_TIME                      datetime    not null
)
    go

