CREATE TABLE BPM_ISMS_ADDITIONAL
(
    FORM_ID                  VARCHAR(50)                NOT NULL
        CONSTRAINT BPM_ISMS_ADDITIONAL_PK
            PRIMARY KEY,
    PROCESS_INSTANCE_ID      VARCHAR(50)                NOT NULL,
    MAIN_FORM_ID             VARCHAR(50)                NOT NULL,
    MAIN_PROCESS_INSTANCE_ID VARCHAR(50)                NOT NULL,
    MAIN_PROCESS_TASK_ID     VARCHAR(50)                NOT NULL,
    REQUESTER_ID             NVARCHAR(50) COLLATE CHINESE_TAIWAN_STROKE_CS_AS NOT NULL,
    REQUESTER                NVARCHAR(50) COLLATE CHINESE_TAIWAN_STROKE_CS_AS NOT NULL,
    ADDITIONAL_SIGNER_ID     NVARCHAR(50) COLLATE CHINESE_TAIWAN_STROKE_CS_AS NOT NULL,
    ADDITIONAL_SIGNER        NVARCHAR(50) COLLATE CHINESE_TAIWAN_STROKE_CS_AS NOT NULL,
    PROCESS_INSTANCE_STATUS  NVARCHAR(1) DEFAULT '0' COLLATE CHINESE_TAIWAN_STROKE_CS_AS NOT NULL,
    ADDITIONAL_SIGN_REASON   NVARCHAR(100) COLLATE CHINESE_TAIWAN_STROKE_CS_AS NOT NULL,
    CREATE_TIME              DATETIME DEFAULT GETDATE() NOT NULL
) GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'BPM_ISMS加簽表', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'加簽表單編號', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'FORM_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'流程實體編號', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'PROCESS_INSTANCE_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'主流程表單編號', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'MAIN_FORM_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'主流程實體編號', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'MAIN_PROCESS_INSTANCE_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'主流程發起加簽任務ID', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'MAIN_PROCESS_TASK_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'原審核人ID', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL', 'COLUMN',
     'REQUESTER_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'原審核人', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL', 'COLUMN',
     'REQUESTER'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'額外簽核人ID', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'ADDITIONAL_SIGNER_ID'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'額外簽核人', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL', 'COLUMN',
     'ADDITIONAL_SIGNER'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'加簽流程實體狀態', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL',
     'COLUMN', 'PROCESS_INSTANCE_STATUS'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'加簽理由', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL', 'COLUMN',
     'ADDITIONAL_SIGN_REASON'
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', N'建立時間', 'SCHEMA', 'DBO', 'TABLE', 'BPM_ISMS_ADDITIONAL', 'COLUMN',
     'CREATE_TIME'
GO

